name: Development

on:
  workflow_call:

jobs:
  dockerBuild:
    name: "Scan Docker image"
    runs-on: ubuntu-latest

    steps:
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: "https://hub.docker.com/repository/docker/kaungmyatsoedev/wops-laravel:${{ github.sha }}"
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"
